**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/contrib/layers/xavier_initializer

**Describe the documentation issue**

According to the documentation the Xavier initializer allows use of both the uniform distribution and the normal distribution.  However, when passing `uniform=False` to `xavier_initializer`, the code in `variance_scaling_initializer` actually uses a truncated normal distribution instead, [code link](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/layers/python/layers/initializers.py#L146).

The fix would consist of adjusting the documentation to provide details about the truncated Normal sampling.<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>


**System information**
- TensorFlow version:
- Doc Link:
https://github.com/tensorflow/tensorflow/commit/3ae375aa92fbb6155f82393735d0b98d8fb9c1b2?diff=split#diff-4ffc4dce469256b24264cb6c7db54363

**Describe the documentation issue**
The link to the TF-GAN tutorial is in tensorflow/contrib/gan/README.md L:59
points to http://https://github.com/tensorflow/models/tree/master/research/gan/tutorial.ipynb but it should point to https://github.com/tensorflow/models/tree/master/research/gan/tutorial.ipynb
The wrong link takes one to some sales page.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
I am using anaconda with python 3 and have tensorflow 1.12 
I am trying to run [this](https://www.tensorflow.org/guide/eager) tutorial example 

Using with code: 
```
from __future__ import absolute_import, division, print_function
import tensorflow as tf
tf.enable_eager_execution()
```

and getting this error 

> raise RuntimeError("tf.placeholder() is not compatible with "
> RuntimeError: tf.placeholder() is not compatible with eager execution.

What am i missing here? **System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 4.5.12
- Python version: 3.5.2
- GPU model and memory: GPU 0 - Intel(R) HD Graphics 620 |  GPU 1 - NVIDIA GeForce 920MX | 8gb RAM

**(tensorflow1) C:\tensorflow1\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record**

Traceback (most recent call last):
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
